### ISSUE TITLE
Choix des données utiles pour la segmentation RFM

### ISSUE THREAD

**Issue by lilifull** [Justine-league/LA-DATA-DREAM-TEAM-equipe-justine#7]

**Comment by Dylanreichart5** [comment]
Création des listes de données nécessaire pour la segmentation clients

**Comment by Dylanreichart5** [comment]
![image](https://user-images.githubusercontent.com/114474867/205902803-ca198eb0-510d-4379-8720-79f3598d8cfd.png)
